all:
	gcc -o qsort-lib qsort-lib.c utils.c
	gcc -o quick-sort quick-sort.c utils.c
	gcc -o quick-insertion quick-insertion.c utils.c
	gcc -o quick-median quick-median.c utils.c
	gcc -o quick-random quick-random.c utils.c
	gcc -o quick-hoare quick-hoare.c utils.c
	gcc -o quick-onerec quick-onerec.c utils.c
	gcc -o quick-find quick-find.c utils.c
	gcc -o quick-nuts-bolts quick-nuts-bolts.c utils.c
clean:
	rm qsort-lib quick-sort quick-insertion quick-median quick-random quick-hoare quick-onerec quick-nuts-bolts
